### PR TITLE
Virtual Microscope upgrade

### PR DESCRIPTION
**Pull request by mtbc**
To be deployed Tuesday morning in concert with #273 for role upgrades.

### CODE REVIEW

**Comment by mtbc** [comment]
```
RUNNING HANDLER [ome.omero_web : omero-web restart omero-web] ********************************************************************************
skipping: [learning.openmicroscopy.org]
```
Had to restart omero-web manually. Now deployed.

**Comment by manics** [comment]
Do you have the full playbook output that shows all changed tasks?

**Comment by mtbc** [comment]
[playbook.log](https://github.com/ome/prod-playbooks/files/4952110/playbook.log)

**Comment by sbesson** [comment]
https://github.com/ome/prod-playbooks/blob/master/learning.yml#L83 would prevent the handlers from restarting the deployment as per https://github.com/ome/ansible-role-omero-web/blob/master/handlers/main.yml#L17. Is there any rationale for disabling this?

**Comment by mtbc** [comment]
Aha, okay, that'll be it, thank you. It was certainly needed for a fresh install to go through smoothly with the playbook as it originally was. Perhaps it's something to do with later tasks installing web stuff like the custom Nginx config? Probably best not to remove it before seeing what it now does with a fresh install and deciding that whatever that is is okay.

**Comment by sbesson** [comment]
Do you want to capture this as an issue for now?

**Comment by mtbc** [comment]
Sure: #276

**Comment by sbesson** [comment]
Thanks

**Pull request merged**
