### PR TITLE
Update the training backup jupyterhub server

### PR DESCRIPTION
**Pull request by manics**
Updates JupyterHub, see
- [x] https://github.com/IDR/ansible-role-idr-jupyter/pull/6

Updates the notebook image to `openmicroscopy/training-notebooks:0.7.2`

### CODE REVIEW

**Comment by pwalczysko** [comment]
```
[0m[0m[0m    - downloading role from https://github.com/ome/ansible-role-java/archive/2.0.3.tar.gz[0m[0m[0m
[0m[0m[0m[31m[0;31m [ERROR]: failed to download the file: HTTP Error 401: UNAUTHORIZED[0m[0m[0m[0m[0m
[0m[0m[0m[31m[0;31m[0m[0m[0m[0m[0m
```
is that the travis error ?

**Comment by manics** [comment]
It's a travis error, restarted the failing job

**Comment by jburel** [comment]
Looked at few notebooks and  the correct version is used. It matches what is currently deployed on idr-analysis/training
Following the "port issues, we will need to update the notebooks to use websockets and deployed the new tagged image.
This is outside this PR. I updated the one in the new repositories but not in training-notebooks

**Comment by sbesson** [comment]
Merging as this is required to fix Travis

**Pull request merged**
