### PR TITLE
Release of www 8 Dec 2020

### PR DESCRIPTION
**Pull request by pwalczysko**
Releasing www as per https://github.com/ome/www.openmicroscopy.org/pull/430#issuecomment-740467403

Deployed on 

  - ome-www-dev
  - ome-www

successfully

### CODE REVIEW

**Comment by pwalczysko** [comment]
failed checks, but can we maybe merge this ?
As I want to open a new release PR cc @sbesson

**Comment by pwalczysko** [comment]
```
docker-compose 1.22.0 has requirement PyYAML<4,>=3.10, but you'll have pyyaml 5.3.1 which is incompatible.[0m
```
maybe this is the reason ?

**Comment by sbesson** [comment]
As mentioned earlier, I don't think we can rely on Travis CI anymore and the priority is now to look into switching into GitHub actions at earliest.

If you want to capture the website,  could you put another commit to capture the latest state of the playbook?

**Comment by pwalczysko** [comment]
https://github.com/ome/prod-playbooks/pull/298/commits/9d7c4582390f6e44915382949bf82ff0302a5260 captures the first repeat of today's release

**Review by sbesson — APPROVED** [review]

**Pull request merged**
