### PR TITLE
Webtagging

### PR DESCRIPTION
**Pull request by pwalczysko**
upgrade webtagging to 3.1.0 as per https://github.com/MicronOxford/webtagging/releases

cc @manics @jburel

### CODE REVIEW

**Comment by pwalczysko** [comment]
@manics unfortunately, I am having

```
RUNNING HANDLER [ome.omero_common : restart omero-web] *************************
fatal: [ome-training-4.openmicroscopy.org]: FAILED! => {"changed": false, "msg": "Unable to restart service omero-web: Job for omero-web.service failed because the control process exited with error code. See \"systemctl status omero-web.service\" and \"journalctl -xe\" for details.\n"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
ome-training-4.openmicroscopy.org : ok=120  changed=3    unreachable=0    failed=1 
```

**Comment by pwalczysko** [comment]
With the last fix, it was deployed on ome-training-4 and works fine also when tested in UI.

**Comment by pwalczysko** [comment]
Deployed and tested on workshop server. All works as expected.

**Comment by pwalczysko** [comment]
Deployed and tested on outreach server. All works as expected.

**Comment by pwalczysko** [comment]
All good here, except the failing travis cc @manics

**Comment by manics** [comment]
It's an ansible-lint error (ansible equivalent of flake8)
```
--> Executing Ansible Lint on /home/travis/build/ome/prod-playbooks/site.yml...

    [ANSIBLE0002] Trailing whitespace

    /home/travis/build/ome/prod-playbooks/omero/training-server/playbook.yml:270
```

**Comment by pwalczysko** [comment]
Good to merge then ?

**Comment by joshmoore** [comment]
LGTM

**Pull request merged**
