### PR TITLE
Upgrade outreach for django

### PR DESCRIPTION
**Pull request by pwalczysko**
cf https://github.com/IDR/deployment/pull/365/files 
commented out webtagging and tagsearch

cc @sbesson @jburel @will-moore

### CODE REVIEW

**Comment by pwalczysko** [comment]
omero-web does not restart

**Comment by pwalczysko** [comment]
I suppose this is because I am not able to "comment out" the webtagging cleanly ?  cc @sbesson @jburel

**Comment by will-moore** [comment]
You'll need to comment out in `omere-web-outreach-webapps.omero`
```
# Autotag
config append -- omero.web.apps '"omero_webtagging_autotag"'
config append -- omero.web.ui.center_plugins '["Auto Tag", "omero_webtagging_autotag/auto_tag_init.js.html", "auto_tag_panel"]'
```

**Comment by sbesson** [comment]
Briefly discussed with @pwalczysko, the underlying error is:

```
Mar 16 14:15:13 ome-training-3 omero[27810]: __import__(urlmodule)
Mar 16 14:15:13 ome-training-3 omero[27810]: File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_webtagging_tagsearch/urls.py", line 2, in <module>
Mar 16 14:15:13 ome-training-3 omero[27810]: from . import views
Mar 16 14:15:13 ome-training-3 omero[27810]: File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_webtagging_tagsearch/views.py", line 6, in <module>
Mar 16 14:15:13 ome-training-3 omero[27810]: from django.core.urlresolvers import reverse
Mar 16 14:15:13 ome-training-3 omero[27810]: ModuleNotFoundError: No module named 'django.core.urlresolvers'
```

I had not thought of https://github.com/ome/prod-playbooks/pull/332#issuecomment-1069271542 which might indeed be one way to fix the issue i.e. do not register the unpatched app in the Web framework.

On the other hand, a secondary issue is that the changes proposed here perform a partial upgrade of the virtual environment, leaving some of the packages installed but incompatible. I think this has the potential for creating brittle scenarios. To some extent we are facing a similar issue in https://github.com/IDR/deployment/pull/364 where we need to replace an app by another one.

At the moment the Ansible OMERO.web role only manages the installation of apps/packages but I will look into extending it to support the uninstallation as well.

**Comment by sbesson** [comment]
With https://github.com/ome/ansible-role-omero-web/pull/42/commits/f8a269e31345dc7494f1c631e529809c604b13bf, I would expect the following diff (requires a re-installation of the roles) would uninstall the unpatched apps:

```diff
diff --git a/omero/training-server/playbook.yml b/omero/training-server/playbook.yml
index 737260a..985e3a5 100644
--- a/omero/training-server/playbook.yml
+++ b/omero/training-server/playbook.yml
@@ -348,8 +348,11 @@
       - "omero-iviewer=={{ omero_iviewer_release }}"
       - "omero-mapr=={{ omero_mapr_release }}"
       - "omero-parade=={{ omero_parade_release }}"
-      - "omero-webtagging-autotag=={{ omero_webtagging_autotag_release }}"
-      - "omero-webtagging-tagsearch=={{ omero_webtagging_tagsearch_release }}"
+
+    omero_web_python_delete:
+      - omero-webtagging-autotag
+      - omero-webtagging-tagsearch
+
 
     ome_training_scripts_release: "{{ ome_training_scripts_release_override | default('0.2.0') }}"
     omero_webtagging_autotag_release: "{{ omero_webtagging_autotag_release_override | default('3.1.0') }}"
diff --git a/requirements.yml b/requirements.yml
index d9476bd..b550924 100644
--- a/requirements.yml
+++ b/requirements.yml
@@ -53,7 +53,8 @@
   version: 0.3.0
 
 - name: ome.omero_web
-  version: 4.0.1
+  src: https://github.com/ome/ansible-role-omero-web/archive/f8a269e31345dc7494f1c631e529809c604b13bf.tar.gz
+  version: 4.1.0
 
 - src: ome.python3_virtualenv
   version: 0.1.2
```

**Comment by pwalczysko** [comment]
> You'll need to comment out in `omere-web-outreach-webapps.omero` or other `.j2` files
> 
> ```
> # Autotag
> config append -- omero.web.apps '"omero_webtagging_autotag"'
> config append -- omero.web.ui.center_plugins '["Auto Tag", "omero_webtagging_autotag/auto_tag_init.js.html", "auto_tag_panel"]'
> ```

commented out all possible config append lines of webtagging. Still the same error.

**Comment by will-moore** [comment]
If you comment out the `omero config append` does that still leave the existing config intact?
Do you need a `omero config remove -- omero.web.apps '"omero_webtagging_autotag"'` etc?

**Comment by pwalczysko** [comment]
closing  To be replaced by https://github.com/ome/prod-playbooks/pull/334

**Pull request closed without merging**
