### PR TITLE
Add ome.sudoers to www playbook

### PR DESCRIPTION
**Pull request by sbesson**
This should allow additional AD groups to get access to this server

### CODE REVIEW

**Comment by sbesson** [comment]
Actually I had to patch the role inline with `s|visudo|/usr/sbin/visudo` in order for the command to complete. I'll open a PR shortly (trying to construct failing tests) but does that ring a bell to you?

**Comment by manics** [comment]
No, it's always worked fine for me, e.g. all the new VMs that used the bootstrap playbook worked https://github.com/ome/prod-playbooks/blob/master/bootstrap/playbook.yml

**Comment by sbesson** [comment]
I have not been able to identify why this server would be different (`RHEL7` vs `CentOS7`?). Opened https://github.com/ome/ansible-role-sudoers/pull/1 with the associate fix used for deploying this change in production.

Leaving the reviewer of this PR to check whether this change is necessary to run the playbook against e.g. the `ome-www-dev` server. If still necessary, I propose to also review/release the role PR and bump the role dependency  before merging.

**Comment by manics** [comment]
I needed https://github.com/ome/ansible-role-sudoers/pull/1 for `ome-www-dev`, I don't know what's different about that server.

**Comment by sbesson** [comment]
@manics thanks for confirming independently. I cut a patch of `ome.sudoers` with the `visudo` fix and bumped the required version in 16f52ed .

**Comment by manics** [comment]
Thanks!

**Pull request merged**
