### PR TITLE
Bump install release versions for SLS Gallery.

### PR DESCRIPTION
**Pull request by mtbc**
Ready to deploy now OMERO 5.6.3 is released.

### CODE REVIEW

**Review by sbesson — APPROVED** [review]
Anything else to do here other than scheduling downtime if needed and deploying?

**Comment by mtbc** [comment]
No, I'll go ahead and deploy.

**Comment by joshmoore** [comment]
:+1: otherwise as https://github.com/ome/prod-playbooks/pull/289#issuecomment-702658260

**Comment by mtbc** [comment]
Now deployed.

**Pull request merged**
