### PR TITLE
mencoder cleanup

### PR DESCRIPTION
**Pull request by jburel**
remove duplicate
Installation already covered by 
```
    - name: OMERO.figure server-side prerequisites, script prerequisites + web server for decoupled OMERO.web
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python-reportlab # For OMERO.figure
        - python-markdown # For OMERO.figure
        - mencoder # For the 'make movie' script
        - scipy
        - python-matplotlib # For "simple frap with figure" script
```

### CODE REVIEW

**Comment by joshmoore** [comment]
Looks good. I assume running under check mode shows no changes?

**Comment by jburel** [comment]
no change noticed

**Comment by joshmoore** [comment]
Cool. (Pasting the final summary line from running with `ansible-playbook ... -C` until we have automated tests is generally useful.)

**Comment by jburel** [comment]
Will do

**Comment by jburel** [comment]
```
TASK [Install Make Movie script Prerequisite | MEncoder - Repo] **************************************************************************************************************
ok: [outreach.openmicroscopy.org]

TASK [OMERO.figure server-side prerequisites, script prerequisites + web server for decoupled OMERO.web] *********************************************************************
ok: [outreach.openmicroscopy.org] => (item=[u'python-reportlab', u'python-markdown', u'mencoder', u'scipy', u'python-matplotlib'])

```

**Pull request merged**
