### PR TITLE
Fix email

### PR DESCRIPTION
**Pull request by pwalczysko**
Following the discussion last week about the demo email, this is an attempt to 

1. remove typos introduced by formatting of the text inside YAML
2. remove links as they are possibly catched by spam filters, leave just one non-clickable link to walkthrough without https beginning
3. simplify the text

cc @jburel @sbesson 

Note: This is done on top of https://github.com/ome/prod-playbooks/pull/373 in order not to downgrade by accident.

The new email body looks as follows:
Screenshot 2023-09-06 at 13 06 44

### CODE REVIEW

**Comment by pwalczysko** [comment]
Deployed on demo successfully (thanks @sbesson ).

The new email looks like (suggestions welcome, cc @jburel - removed the links and simplified, of course have to leave the username and password though....)
Screenshot 2023-09-06 at 13 06 44

**Comment by pwalczysko** [comment]
ditto https://github.com/ome/prod-playbooks/pull/373#issuecomment-1719448010

**Comment by sbesson** [comment]
Echoing my suspicion at https://github.com/ome/prod-playbooks/pull/373#issuecomment-1719460096:
- the [last successful build](https://github.com/ome/prod-playbooks/actions/runs/6096104583) was on Sep, 6, 2023 11:50 GMT+1 
- the [following build](https://github.com/ome/prod-playbooks/actions/runs/6096708747) failed at Sep, 6, 2023 12:56 GMT+1 on the metrics tests.
- `omero-certificates 0.3.0` was deployed on PyPI at 12:43 GMT +1

**Comment by pwalczysko** [comment]
Any objections to merge ? This has been already deployed and shown to work on demo server. If not merged, the danger is that we revert to the broken email from before by mistake cc @jburel @sbesson

**Review by sbesson — APPROVED** [review]
At least nothing strikes me as a concern. If these changes are already applied, I agree that keeping playbooks out of date puts you guys at risk of inadvertently downgrading changes on production systems.

**Pull request merged**
