### PR TITLE
Bump omero_web_release to 5.14.1 everywhere

### PR DESCRIPTION
**Pull request by will-moore**
This bumps omero-web on nightshade, demo-server, training-server and sls-gallery.

### CODE REVIEW

**Comment by jburel** [comment]
@will-moore did you run the playbook?
nightshade seems to still be at 5.14.0

**Comment by will-moore** [comment]
No, I didn't run the playbook. I don't know how, and I assumed that happens after merging the PR?

**Comment by jburel** [comment]
no this is manual

**Comment by sbesson** [comment]
Thanks @will-moore, starting with `demo`, I should be able to update most OMERO.web deployments. The only exception might be `training-server` which might wait on @pwalczysko's return to confirm whether he is happy to upgrade before the next OMERO workshop.

**Comment by sbesson** [comment]
Thanks @will-moore. Leaving @pwalczysko to capture the training servers upgrade.

**Pull request merged**
