### PR TITLE
Bump install release versions for demo servers.

### PR DESCRIPTION
**Pull request by mtbc**
Ready to deploy now OMERO 5.6.3 is released.

### CODE REVIEW

**Comment by sbesson** [comment]
Changes make sense. Is the plan to deploy first on `pub-omero` followed by an upgrade of `demo.openmicroscopy.org` ?

**Comment by mtbc** [comment]
It is.

**Review by sbesson — APPROVED** [review]

**Comment by joshmoore** [comment]
Also makes sense to me, though it'd be great if dependabot could open these PRS :) I assume we're holding off to merge until it's deployed.

**Comment by mtbc** [comment]
Now deployed on both.

**Pull request merged**
